### ISSUE TITLE
It broked :(

### ISSUE THREAD

**Issue by epeld** [triforkse/game-of-life-redux#1]
``` bash
EriksMacBookAir:game-of-life-redux peldan$ npm start

> redux-async-example@0.0.0 start /Users/peldan/Documents/Code/game-of-life-redux
> node server.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'body-parser'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/peldan/Documents/Code/game-of-life-redux/server.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

npm ERR! redux-async-example@0.0.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the redux-async-example@0.0.0 start script.
npm ERR! This is most likely a problem with the redux-async-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-async-example
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/peldan/Documents/Code/game-of-life-redux
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/peldan/Documents/Code/game-of-life-redux/npm-debug.log
npm ERR! not ok code 0
EriksMacBookAir:game-of-life-redux peldan$ 
```

**Comment by swemail** [comment]
Should be solved now :)
